# docker compose -f misc/docker-compose.dev.yml --project-name pixconf up -d --remove-orphans --scale agent=3

version: '3.9'

services:

  hub:
    image: ubuntu:jammy
    command: /build/pixconf-hub-linux-amd64
    restart: unless-stopped
    volumes:
      - ./build/:/build

  agent:
    image: ubuntu:jammy
    command: /build/pixconf-agent-linux-amd64
    restart: unless-stopped
    volumes:
      - ./build/:/build
