# docker compose -f docker-compose.dev.yml --project-name pixconf up -d --remove-orphans

version: '3.9'

volumes:
  postgresql: {}

services:
  # docker exec -it pixconf-postgresql-1 psql -U pixconf -W pixconf
  postgresql:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=pixconf
      - POSTGRES_PASSWORD=pixconf
      - POSTGRES_DB=pixconf
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data

  secrets:
    image: ubuntu:jammy
    command: /build/pixconf-secrets-linux-amd64
    environment:
      - SECRETS_MASTER_ENCRYPTION_KEY=5goenwVdrZTVfJM9r6oVy5fSNo4eL/MED/YBgK3tS4o=
      - SECRETS_DATABASE_URL=postgres://pixconf:pixconf@postgresql:5432/pixconf
    volumes:
      - ./build/:/build
    ports:
      - '8142:8142'
