# docker compose -f docker-compose.dev.yml --project-name pixconf up -d --remove-orphans

version: '3.9'

volumes:
  postgresql: {}

services:
  # docker exec -it pixconf-postgresql-1 psql -U pixconf -W pixconf
  postgresql:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=pixconf
      - POSTGRES_PASSWORD=pixconf
      - POSTGRES_DB=pixconf
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
