// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: internal/protos/src/secrets.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretState int32

const (
	SecretState_normal  SecretState = 0
	SecretState_hidden  SecretState = 1
	SecretState_deleted SecretState = 2
)

// Enum value maps for SecretState.
var (
	SecretState_name = map[int32]string{
		0: "normal",
		1: "hidden",
		2: "deleted",
	}
	SecretState_value = map[string]int32{
		"normal":  0,
		"hidden":  1,
		"deleted": 2,
	}
)

func (x SecretState) Enum() *SecretState {
	p := new(SecretState)
	*p = x
	return p
}

func (x SecretState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protos_src_secrets_proto_enumTypes[0].Descriptor()
}

func (SecretState) Type() protoreflect.EnumType {
	return &file_internal_protos_src_secrets_proto_enumTypes[0]
}

func (x SecretState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretState.Descriptor instead.
func (SecretState) EnumDescriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{0}
}

type SecretCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State       SecretState `protobuf:"varint,1,opt,name=state,proto3,enum=SecretState" json:"state,omitempty"`
	Description string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string    `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Alias       []string    `protobuf:"bytes,4,rep,name=alias,proto3" json:"alias,omitempty"`
}

func (x *SecretCreateRequest) Reset() {
	*x = SecretCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCreateRequest) ProtoMessage() {}

func (x *SecretCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCreateRequest.ProtoReflect.Descriptor instead.
func (*SecretCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *SecretCreateRequest) GetState() SecretState {
	if x != nil {
		return x.State
	}
	return SecretState_normal
}

func (x *SecretCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecretCreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SecretCreateRequest) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

type SecretCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	State     SecretState            `protobuf:"varint,3,opt,name=state,proto3,enum=SecretState" json:"state,omitempty"`
	Tags      []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Alias     []string               `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
}

func (x *SecretCreateResponse) Reset() {
	*x = SecretCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCreateResponse) ProtoMessage() {}

func (x *SecretCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCreateResponse.ProtoReflect.Descriptor instead.
func (*SecretCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *SecretCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretCreateResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretCreateResponse) GetState() SecretState {
	if x != nil {
		return x.State
	}
	return SecretState_normal
}

func (x *SecretCreateResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SecretCreateResponse) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

type SecretUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State       SecretState `protobuf:"varint,2,opt,name=state,proto3,enum=SecretState" json:"state,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string    `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Alias       []string    `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
}

func (x *SecretUpdateRequest) Reset() {
	*x = SecretUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretUpdateRequest) ProtoMessage() {}

func (x *SecretUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretUpdateRequest.ProtoReflect.Descriptor instead.
func (*SecretUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *SecretUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretUpdateRequest) GetState() SecretState {
	if x != nil {
		return x.State
	}
	return SecretState_normal
}

func (x *SecretUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecretUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SecretUpdateRequest) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

type SecretUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State       SecretState `protobuf:"varint,2,opt,name=state,proto3,enum=SecretState" json:"state,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []string    `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Alias       []string    `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
}

func (x *SecretUpdateResponse) Reset() {
	*x = SecretUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretUpdateResponse) ProtoMessage() {}

func (x *SecretUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretUpdateResponse.ProtoReflect.Descriptor instead.
func (*SecretUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *SecretUpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretUpdateResponse) GetState() SecretState {
	if x != nil {
		return x.State
	}
	return SecretState_normal
}

func (x *SecretUpdateResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecretUpdateResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SecretUpdateResponse) GetAlias() []string {
	if x != nil {
		return x.Alias
	}
	return nil
}

type SecretCreateVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretId string            `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	State    SecretState       `protobuf:"varint,2,opt,name=state,proto3,enum=SecretState" json:"state,omitempty"`
	Active   bool              `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Ttl      uint32            `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Value    map[string]string `protobuf:"bytes,5,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SecretCreateVersionRequest) Reset() {
	*x = SecretCreateVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCreateVersionRequest) ProtoMessage() {}

func (x *SecretCreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCreateVersionRequest.ProtoReflect.Descriptor instead.
func (*SecretCreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *SecretCreateVersionRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SecretCreateVersionRequest) GetState() SecretState {
	if x != nil {
		return x.State
	}
	return SecretState_normal
}

func (x *SecretCreateVersionRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *SecretCreateVersionRequest) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *SecretCreateVersionRequest) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

type SecretCreateVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretId string      `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version  uint32      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	State    SecretState `protobuf:"varint,3,opt,name=state,proto3,enum=SecretState" json:"state,omitempty"`
}

func (x *SecretCreateVersionResponse) Reset() {
	*x = SecretCreateVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretCreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretCreateVersionResponse) ProtoMessage() {}

func (x *SecretCreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretCreateVersionResponse.ProtoReflect.Descriptor instead.
func (*SecretCreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *SecretCreateVersionResponse) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SecretCreateVersionResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretCreateVersionResponse) GetState() SecretState {
	if x != nil {
		return x.State
	}
	return SecretState_normal
}

type SecretTransitEncryptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecretTransitEncryptRequest) Reset() {
	*x = SecretTransitEncryptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretTransitEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTransitEncryptRequest) ProtoMessage() {}

func (x *SecretTransitEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTransitEncryptRequest.ProtoReflect.Descriptor instead.
func (*SecretTransitEncryptRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *SecretTransitEncryptRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SecretTransitEncryptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecretTransitEncryptResponse) Reset() {
	*x = SecretTransitEncryptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretTransitEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTransitEncryptResponse) ProtoMessage() {}

func (x *SecretTransitEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTransitEncryptResponse.ProtoReflect.Descriptor instead.
func (*SecretTransitEncryptResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *SecretTransitEncryptResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SecretTransitDecryptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecretTransitDecryptRequest) Reset() {
	*x = SecretTransitDecryptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretTransitDecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTransitDecryptRequest) ProtoMessage() {}

func (x *SecretTransitDecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTransitDecryptRequest.ProtoReflect.Descriptor instead.
func (*SecretTransitDecryptRequest) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *SecretTransitDecryptRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SecretTransitDecryptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecretTransitDecryptResponse) Reset() {
	*x = SecretTransitDecryptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_src_secrets_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretTransitDecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTransitDecryptResponse) ProtoMessage() {}

func (x *SecretTransitDecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_src_secrets_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTransitDecryptResponse.ProtoReflect.Descriptor instead.
func (*SecretTransitDecryptResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_src_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *SecretTransitDecryptResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_internal_protos_src_secrets_proto protoreflect.FileDescriptor

var file_internal_protos_src_secrets_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0xaf, 0x01, 0x0a,
	0x14, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x95,
	0x01, 0x0a, 0x13, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22,
	0xff, 0x01, 0x0a, 0x1a, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x3c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x78, 0x0a, 0x1b, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x31, 0x0a, 0x1b, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32,
	0x0a, 0x1c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x31, 0x0a, 0x1b, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x1c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x32, 0x0a, 0x0b, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02, 0x32, 0xfd, 0x02,
	0x0a, 0x07, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x1c, 0x2e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x1c,
	0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x44, 0x65,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x44, 0x65, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_protos_src_secrets_proto_rawDescOnce sync.Once
	file_internal_protos_src_secrets_proto_rawDescData = file_internal_protos_src_secrets_proto_rawDesc
)

func file_internal_protos_src_secrets_proto_rawDescGZIP() []byte {
	file_internal_protos_src_secrets_proto_rawDescOnce.Do(func() {
		file_internal_protos_src_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_src_secrets_proto_rawDescData)
	})
	return file_internal_protos_src_secrets_proto_rawDescData
}

var file_internal_protos_src_secrets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protos_src_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_protos_src_secrets_proto_goTypes = []interface{}{
	(SecretState)(0),                     // 0: SecretState
	(*SecretCreateRequest)(nil),          // 1: SecretCreateRequest
	(*SecretCreateResponse)(nil),         // 2: SecretCreateResponse
	(*SecretUpdateRequest)(nil),          // 3: SecretUpdateRequest
	(*SecretUpdateResponse)(nil),         // 4: SecretUpdateResponse
	(*SecretCreateVersionRequest)(nil),   // 5: SecretCreateVersionRequest
	(*SecretCreateVersionResponse)(nil),  // 6: SecretCreateVersionResponse
	(*SecretTransitEncryptRequest)(nil),  // 7: SecretTransitEncryptRequest
	(*SecretTransitEncryptResponse)(nil), // 8: SecretTransitEncryptResponse
	(*SecretTransitDecryptRequest)(nil),  // 9: SecretTransitDecryptRequest
	(*SecretTransitDecryptResponse)(nil), // 10: SecretTransitDecryptResponse
	nil,                                  // 11: SecretCreateVersionRequest.ValueEntry
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_internal_protos_src_secrets_proto_depIdxs = []int32{
	0,  // 0: SecretCreateRequest.state:type_name -> SecretState
	12, // 1: SecretCreateResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: SecretCreateResponse.state:type_name -> SecretState
	0,  // 3: SecretUpdateRequest.state:type_name -> SecretState
	0,  // 4: SecretUpdateResponse.state:type_name -> SecretState
	0,  // 5: SecretCreateVersionRequest.state:type_name -> SecretState
	11, // 6: SecretCreateVersionRequest.value:type_name -> SecretCreateVersionRequest.ValueEntry
	0,  // 7: SecretCreateVersionResponse.state:type_name -> SecretState
	1,  // 8: Secrets.CreateSecret:input_type -> SecretCreateRequest
	3,  // 9: Secrets.UpdateSecret:input_type -> SecretUpdateRequest
	5,  // 10: Secrets.CreateSecretVersion:input_type -> SecretCreateVersionRequest
	7,  // 11: Secrets.TransitEncrypt:input_type -> SecretTransitEncryptRequest
	9,  // 12: Secrets.TransitDecrypt:input_type -> SecretTransitDecryptRequest
	2,  // 13: Secrets.CreateSecret:output_type -> SecretCreateResponse
	4,  // 14: Secrets.UpdateSecret:output_type -> SecretUpdateResponse
	6,  // 15: Secrets.CreateSecretVersion:output_type -> SecretCreateVersionResponse
	8,  // 16: Secrets.TransitEncrypt:output_type -> SecretTransitEncryptResponse
	10, // 17: Secrets.TransitDecrypt:output_type -> SecretTransitDecryptResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_protos_src_secrets_proto_init() }
func file_internal_protos_src_secrets_proto_init() {
	if File_internal_protos_src_secrets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_src_secrets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretCreateVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretCreateVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretTransitEncryptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretTransitEncryptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretTransitDecryptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_src_secrets_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretTransitDecryptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_src_secrets_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_src_secrets_proto_goTypes,
		DependencyIndexes: file_internal_protos_src_secrets_proto_depIdxs,
		EnumInfos:         file_internal_protos_src_secrets_proto_enumTypes,
		MessageInfos:      file_internal_protos_src_secrets_proto_msgTypes,
	}.Build()
	File_internal_protos_src_secrets_proto = out.File
	file_internal_protos_src_secrets_proto_rawDesc = nil
	file_internal_protos_src_secrets_proto_goTypes = nil
	file_internal_protos_src_secrets_proto_depIdxs = nil
}
