name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  test:
    needs: lint
    strategy:
      matrix:
        scenario: ["test-full", "test-pure"]
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Run tests
        run: make ${{ matrix.scenario}}
      
      - name: Publish coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
